### ISSUE TITLE
Feature request: Show precise (not relative) expiration dates of offers

### ISSUE THREAD

**Issue by bmp412** [ElTav/AmexOffers#4]
It would be helpful to see absolute dates for the expiry of Amex Offers. For example, I see "expires in 11 days" and "expires tomorrow", then I need to reference the script execution date to figure out the actual date.

**Comment by ElTav** [comment]
Good idea! Just added it in eb749510f990b75b586a6ac72dac86b68d90b06c

**Comment by bmp412** [comment]
Awesome! Thank you so much! I end up importing the CSV to a Google Sheet
each time for viewing, filtering, editing, etc. What do you think about
automating the import process to go right to Sheets? You'd need to handle
Google Auth and everything for permissions, but it would be pretty cool to
cut down some steps.

**Comment by ElTav** [comment]
Of course! That's not super high on my priority list at the moment, but if you wanted to look into it and open a PR I'd be happy to take a look?
